# Generated by Django 6.0.2 on 2026-06-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='equipment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
