# Generated by Django 6.0.2 on 2026-06-21 16:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_purchasedprogram'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchasedprogram',
            unique_together={('user', 'program')},
        ),
    ]
