# Generated by Django 6.0.2 on 2026-06-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_purchasedprogram_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='category',
            field=models.CharField(choices=[('HOME', 'Home Workout'), ('GYM', 'Gym Workout')], default='HOME', max_length=10),
        ),
        migrations.AddField(
            model_name='program',
            name='difficulty',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=20),
        ),
        migrations.AddField(
            model_name='program',
            name='duration_weeks',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='program',
            name='recommended_schedule',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='video',
            name='is_preview',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='week_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
