# Generated by Django 6.0.2 on 2026-06-27 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_review_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['order']},
        ),
    ]
